import { Leaf, Cpu, BookOpen, FlaskConical, Globe, Shield } from 'lucide-react'

export type Paper = {
  id: number
  year: number
  month: string
  type: 'Journal' | 'Conference' | 'Review'
  title: string
  authors: string
  venue: string
  volume?: string
  issn?: string
  doi?: string
  pages?: string
  tags: string[]
  url: string
  color: string
  icon: any
}

export const PAPERS: Paper[] = [
  {
    id: 1,
    year: 2024,
    month: 'Oct',
    type: 'Journal',
    title: 'Smart Farming with YOLO: Predicting the Density of Weeds and Crops for Precision Agriculture',
    authors: 'Sachin Balawant Takmare, Mukesh Shrimali, Rahul Ambekar, Sadanand Shelgaonkar, Shivshankar Kore, Ganesh Gourshete',
    venue: 'International Journal of Environmental & Agriculture Research (IJOEAR)',
    volume: 'Volume 6, Issue 10, 2024',
    issn: 'ISSN: 2454-1850',
    pages: 'pp. 14–25',
    tags: ['YOLO', 'Precision Agriculture', 'Weed Detection', 'Deep Learning'],
    url: 'https://ijoear.com',
    color: '#1A6B48',
    icon: Leaf,
  },
  {
    id: 2,
    year: 2024,
    month: 'Aug',
    type: 'Journal',
    title: 'Transforming Farming with CNNs: Accurate Crop and Weed Classification',
    authors: 'Sachin Balawant Takmare, Mukesh Shrimali, Rahul K. Ambekar, Sagar B. Patil, Pramod A. Kharade, Kuldeep Vayadande',
    venue: 'International Journal of Intelligent Systems and Applications in Engineering (IJISAE)',
    volume: 'Volume 12, Issue 4, 2024',
    issn: 'ISSN: 2147-6799',
    pages: 'pp. 1484–1490',
    tags: ['CNN', 'Crop Classification', 'Weed Classification', 'Precision Farming'],
    url: 'https://ijisae.org',
    color: '#0D1F3C',
    icon: Leaf,
  },
  {
    id: 3,
    year: 2024,
    month: 'Aug',
    type: 'Journal',
    title: 'A Deep Learning Approach to Efficient Crop and Weed Classification for Precision Farming',
    authors: 'Sachin Balawant Takmare et al.',
    venue: 'International Journal of Computer Sciences and Engineering (IJCSE)',
    volume: 'Volume 12, Issue 6, 2024',
    issn: 'E-ISSN: 2347-2693',
    pages: 'pp. 30–43',
    tags: ['Deep Learning', 'CNN', 'Crop & Weed', 'Precision Farming'],
    url: 'https://www.ijcseonline.org',
    color: '#1A3560',
    icon: Cpu,
  },
  {
    id: 4,
    year: 2024,
    month: 'Aug',
    type: 'Journal',
    title: 'Plant Species and Weed Classification for Precision Agriculture Using CNN',
    authors: 'Sachin Balawant Takmare et al.',
    venue: 'International Journal of Research and Analytical Reviews (IJRAR)',
    volume: 'Volume 11, Issue 2, 2024',
    issn: 'E-ISSN: 2348-1269 | P-ISSN: 2349-5138',
    pages: 'pp. 239–248',
    tags: ['CNN', 'Plant Species', 'Weed Classification', 'Agriculture'],
    url: 'https://ijrar.org',
    color: '#2D5B8A',
    icon: Leaf,
  },
  {
    id: 5,
    year: 2024,
    month: 'Aug',
    type: 'Journal',
    title: 'Finite Automata Application in String Identification',
    authors: 'Sachin Balawant Takmare et al.',
    venue: 'The Indian Journal of Technical Education — Published by Indian Society for Technical Education',
    volume: 'Volume 47, Special Issue No. 1, August 2024',
    issn: 'ISSN: 0971-3034',
    tags: ['Finite Automata', 'String Theory', 'Formal Languages', 'Theory of Computation'],
    url: 'https://iste.org.in',
    color: '#5C3A1A',
    icon: BookOpen,
  },
  {
    id: 6,
    year: 2024,
    month: 'Aug',
    type: 'Journal',
    title: 'Machine Learning Models in Precision Agriculture',
    authors: 'Sachin Balawant Takmare et al.',
    venue: 'Indian Journal of Technical Education — Published by Indian Society for Technical Education',
    volume: 'Volume 47, Special Issue No. 1, August 2024',
    issn: 'ISSN: 0971-3034',
    tags: ['Machine Learning', 'Precision Agriculture', 'Smart Farming'],
    url: 'https://iste.org.in',
    color: '#1A6B48',
    icon: FlaskConical,
  },
  {
    id: 7,
    year: 2024,
    month: 'Mar',
    type: 'Conference',
    title: 'MetaCampus: Advancing Online Education with Virtual Classroom',
    authors: 'Sachin Balawant Takmare et al.',
    venue: 'IEEE — 3rd International Conference for Innovation in Technology (INOCON 2024)',
    volume: '2024',
    issn: '979-8-3503-8193-1/24',
    tags: ['Virtual Reality', 'Online Education', 'Metaverse', 'IEEE'],
    url: 'https://ieeexplore.ieee.org',
    color: '#0D1F3C',
    icon: Globe,
  },
  {
    id: 8,
    year: 2023,
    month: 'Jul',
    type: 'Conference',
    title: 'Dodging Turtis — NFT Gaming on Blockchain',
    authors: 'Sachin Balawant Takmare et al.',
    venue: 'IEEE — World Conference on Communication & Computing (WCONF 2023)',
    volume: '2023',
    issn: '979-8-3503-1120-4/23',
    tags: ['NFT', 'Blockchain', 'Gaming', 'IEEE', 'Web3'],
    url: 'https://ieeexplore.ieee.org',
    color: '#3A2A6A',
    icon: Cpu,
  },
  {
    id: 9,
    year: 2022,
    month: 'Apr',
    type: 'Journal',
    title: 'Network Monitoring and System Diagnostic Suite',
    authors: 'Parth Vora, Harvinder Singh, Royston Rodrigues, Lavleen Jain, Prof. Sachin Takmare (Project Guide)',
    venue: 'International Journal for Research in Applied Science & Engineering Technology (IJRASET)',
    volume: 'Volume 10, Issue IV, April 2022',
    issn: 'ISSN: 2321-9653 | SJ Impact Factor: 7.538',
    tags: ['Network Monitoring', 'System Diagnostics', 'Computer Networks'],
    url: 'https://www.ijraset.com',
    color: '#2D5B8A',
    icon: Globe,
  },
  {
    id: 10,
    year: 2022,
    month: '',
    type: 'Journal',
    title: 'Sickle Cell Anemia Diagnosis Using Microscopic Images',
    authors: 'Sachin Balawant Takmare et al.',
    venue: 'Neuroquantology',
    volume: 'Volume 20, Issue 17',
    issn: 'E-ISSN: 1303-5150',
    tags: ['Medical Imaging', 'Deep Learning', 'Sickle Cell Anemia', 'Diagnosis'],
    url: 'https://www.neuroquantology.com',
    color: '#7A1A1A',
    icon: FlaskConical,
  },
  {
    id: 11,
    year: 2017,
    month: 'Jun',
    type: 'Journal',
    title: 'Dynamic Analysis of Web System by Using Model-Based Testing and Process Crawler Model',
    authors: 'Nayan Mulla, Sachin B. Takmare, Pramod A. Kharade',
    venue: 'International Journal of Engineering and Computer Science (IJECS)',
    volume: 'Volume 6, Issue 6, June 2017',
    issn: 'ISSN: 2319-7242',
    doi: 'DOI: 10.18535/ijecs/v6i6.47',
    pages: 'pp. 21833–21837',
    tags: ['Web Testing', 'Model-Based Testing', 'Process Crawler', 'Dynamic Analysis'],
    url: 'https://ijecs.in',
    color: '#1A3560',
    icon: Globe,
  },
  {
    id: 12,
    year: 2017,
    month: 'Jun',
    type: 'Review',
    title: 'A Review — Dynamic Analysis of Web System by Using Model-Based Testing and Process Crawler Model',
    authors: 'Nayan Mulla, Sachin B. Takmare, Pramod A. Kharade',
    venue: 'International Journal of Engineering Research & Technology (IJERT)',
    volume: 'Volume 6, Issue 6, June 2017',
    issn: 'ISSN: 2278-0181',
    tags: ['Web Systems', 'Model-Based Testing', 'Software Engineering', 'Review'],
    url: 'https://www.ijert.org',
    color: '#0D1F3C',
    icon: BookOpen,
  },
  {
    id: 13,
    year: 2017,
    month: 'Feb',
    type: 'Review',
    title: 'Review of Existing Methods in K-means Clustering Algorithm',
    authors: 'Kavita Shiudkar, Sachin Takmare',
    venue: 'International Research Journal of Engineering and Technology (IRJET)',
    volume: 'Volume 4, Issue 2, February 2017',
    issn: 'e-ISSN: 2395-0056 | p-ISSN: 2395-0072',
    tags: ['K-means Clustering', 'Machine Learning', 'Clustering Algorithms', 'Review'],
    url: 'https://www.irjet.net',
    color: '#2D5B8A',
    icon: Cpu,
  },
  {
    id: 14,
    year: 2012,
    month: 'Nov',
    type: 'Journal',
    title: 'Voice Based Watermarking Technique for Relational Databases',
    authors: 'Sachin Balawant Takmare, Ravindra Kumar Gupta, Gajendra Singh Chandel',
    venue: 'International Journal of Scientific & Technology Research',
    volume: 'Volume 1, Issue 10, November 2012',
    issn: 'ISSN: 2277-8616',
    tags: ['Database Watermarking', 'Voice Watermark', 'Data Security', 'Relational Database'],
    url: 'https://www.ijstr.org',
    color: '#5C3A1A',
    icon: Shield,
  },
]

export const RESEARCH_STATS = {
  totalPublications: PAPERS.length,
  journalPapers: PAPERS.filter(p => p.type === 'Journal').length,
  conferencePapers: PAPERS.filter(p => p.type === 'Conference').length,
  reviewArticles: PAPERS.filter(p => p.type === 'Review').length,
}

export const THESIS_DETAILS = {
  title: 'Precision Farming: CNN-Based System for Crop and Weed Classification and Density Analysis',
  description: 'Doctoral thesis submitted to Pacific University, Udaipur (2024). Developed a Convolutional Neural Network system that automates crop-weed classification from field imagery and employs YOLO-based density estimation for precision herbicide deployment — reducing chemical overuse and improving agricultural sustainability.',
  tags: ['CNN', 'YOLO', 'Precision Agriculture', 'Deep Learning', 'Computer Vision', 'PhD Research'],
  details: [
    { k: 'University', v: 'Pacific University, Udaipur' },
    { k: 'Awarded', v: '2024' },
    { k: 'Domain', v: 'AI · Machine Learning · Precision Agriculture' },
    { k: 'Method', v: 'Convolutional Neural Networks (CNN)' },
    { k: 'Detection', v: 'YOLO-based density estimation' },
    { k: 'Patent', v: 'Application No: 202421045939 (Published)' },
    { k: 'Copyright', v: 'Diary No: 14704/2024-CO/SW' },
  ],
}

export const HERO_STATS = [
  { label: 'Total Publications', icon: 'BookOpen' },
  { label: 'Journal Papers', icon: 'FileText' },
  { label: 'Conference Papers', icon: 'Users' },
  { label: 'Review Articles', icon: 'Award' },
]

export const TYPES = ['All', 'Journal', 'Conference', 'Review'] as const
export type FilterType = typeof TYPES[number]